//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByeMoney.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByeMoney.API.Resources.ApiErrors", typeof(ApiErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید محرمانه Strapi JWT در تنظیمات یافت نشد. لطفاً &apos;Strapi:JwtSecret&apos; را تنظیم کنید..
        /// </summary>
        public static string Auth_JwtSecretMissing {
            get {
                return ResourceManager.GetString("Auth_JwtSecretMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای قانون کسب‌وکار.
        /// </summary>
        public static string Middleware_BusinessRuleViolationTitle {
            get {
                return ResourceManager.GetString("Middleware_BusinessRuleViolationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای داخلی سرور.
        /// </summary>
        public static string Middleware_InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("Middleware_InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string Middleware_NotFoundTitle {
            get {
                return ResourceManager.GetString("Middleware_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی غیرمنتظره رخ داد..
        /// </summary>
        public static string Middleware_UnexpectedErrorMessage {
            get {
                return ResourceManager.GetString("Middleware_UnexpectedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای اعتبارسنجی.
        /// </summary>
        public static string Middleware_ValidationErrorTitle {
            get {
                return ResourceManager.GetString("Middleware_ValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه سند کاربر (documentId) در توکن یافت نشد..
        /// </summary>
        public static string Auth_DocumentIdClaimMissing {
            get {
                return ResourceManager.GetString("Auth_DocumentIdClaimMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم احراز هویت.
        /// </summary>
        public static string Middleware_UnauthorizedTitle {
            get {
                return ResourceManager.GetString("Middleware_UnauthorizedTitle", resourceCulture);
            }
        }
    }
}
