//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByeMoney.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByeMoney.Application.Resources.ApplicationErrors", typeof(ApplicationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تأیید شده ({0}) با مبلغ درخواست افزایش موجودی ({1}) مطابقت ندارد..
        /// </summary>
        public static string TopUpRequest_AmountMismatch {
            get {
                return ResourceManager.GetString("TopUpRequest_AmountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ افزایش موجودی باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_AmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_AmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پیگیری کاربر الزامی است..
        /// </summary>
        public static string TopUpRequest_ClientReferenceCodeRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_ClientReferenceCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تأیید شده باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_ConfirmedAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_ConfirmedAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تراکنش خارجی الزامی است..
        /// </summary>
        public static string TopUpRequest_ExternalTransactionIdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_ExternalTransactionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه درخواست افزایش موجودی الزامی است..
        /// </summary>
        public static string TopUpRequest_IdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست افزایش موجودی با شناسه «{0}» یافت نشد..
        /// </summary>
        public static string TopUpRequest_NotFound {
            get {
                return ResourceManager.GetString("TopUpRequest_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت نامعتبر است..
        /// </summary>
        public static string TopUpRequest_PaymentMethodInvalid {
            get {
                return ResourceManager.GetString("TopUpRequest_PaymentMethodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلیل رد درخواست الزامی است..
        /// </summary>
        public static string TopUpRequest_RejectionReasonRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر الزامی است..
        /// </summary>
        public static string TopUpRequest_UserIdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه خارجی کاربر الزامی است..
        /// </summary>
        public static string User_ExternalUserIdRequired {
            get {
                return ResourceManager.GetString("User_ExternalUserIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه خارجی کاربر نباید بیشتر از ۱۰۰ کاراکتر باشد..
        /// </summary>
        public static string User_ExternalUserIdMaxLength {
            get {
                return ResourceManager.GetString("User_ExternalUserIdMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شناسه خارجی قبلاً ثبت شده است..
        /// </summary>
        public static string User_ExternalUserIdAlreadyExists {
            get {
                return ResourceManager.GetString("User_ExternalUserIdAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام کاربر نباید بیشتر از ۱۰۰ کاراکتر باشد..
        /// </summary>
        public static string User_FirstNameMaxLength {
            get {
                return ResourceManager.GetString("User_FirstNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی کاربر نباید بیشتر از ۱۰۰ کاراکتر باشد..
        /// </summary>
        public static string User_LastNameMaxLength {
            get {
                return ResourceManager.GetString("User_LastNameMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to فرمت ایمیل نامعتبر است..
        /// </summary>
        public static string User_EmailInvalidFormat {
            get {
                return ResourceManager.GetString("User_EmailInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ایمیل نباید بیشتر از ۲۵۵ کاراکتر باشد..
        /// </summary>
        public static string User_EmailMaxLength {
            get {
                return ResourceManager.GetString("User_EmailMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل معتبر نیست..
        /// </summary>
        public static string User_PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("User_PhoneInvalidFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل الزامی است..
        /// </summary>
        public static string User_PhoneRequired {
            get {
                return ResourceManager.GetString("User_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شماره موبایل قبلاً ثبت شده است..
        /// </summary>
        public static string User_PhoneAlreadyExists {
            get {
                return ResourceManager.GetString("User_PhoneAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربر نامعتبر است..
        /// </summary>
        public static string User_UserTypeInvalid {
            get {
                return ResourceManager.GetString("User_UserTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر الزامی است..
        /// </summary>
        public static string Wallet_UserIdRequired {
            get {
                return ResourceManager.GetString("Wallet_UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر احراز هویت نشده است یا شناسه کاربر وجود ندارد..
        /// </summary>
        public static string Wallet_UserNotAuthenticated {
            get {
                return ResourceManager.GetString("Wallet_UserNotAuthenticated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربر با شناسه خارجی «{0}» در سامانه طرح الهی یافت نشد..
        /// </summary>
        public static string User_NotFoundInTarhElahi {
            get {
                return ResourceManager.GetString("User_NotFoundInTarhElahi", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر خریدار الزامی است..
        /// </summary>
        public static string CoursePurchase_BuyerUserIdRequired {
            get {
                return ResourceManager.GetString("CoursePurchase_BuyerUserIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه دوره آموزشی الزامی است..
        /// </summary>
        public static string CoursePurchase_ExternalCourseIdRequired {
            get {
                return ResourceManager.GetString("CoursePurchase_ExternalCourseIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه دوره آموزشی نباید بیشتر از ۱۰۰ کاراکتر باشد..
        /// </summary>
        public static string CoursePurchase_ExternalCourseIdMaxLength {
            get {
                return ResourceManager.GetString("CoursePurchase_ExternalCourseIdMaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شما قبلاً این دوره آموزشی را خریداری کرده‌اید..
        /// </summary>
        public static string CoursePurchase_AlreadyPurchased {
            get {
                return ResourceManager.GetString("CoursePurchase_AlreadyPurchased", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول برای خرید این دوره کافی نیست. موجودی: {0}، مبلغ مورد نیاز: {1}..
        /// </summary>
        public static string CoursePurchase_InsufficientBalance {
            get {
                return ResourceManager.GetString("CoursePurchase_InsufficientBalance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دوره آموزشی مورد نظر یافت نشد..
        /// </summary>
        public static string CoursePurchase_CourseNotFound {
            get {
                return ResourceManager.GetString("CoursePurchase_CourseNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دوره آموزشی در حال حاضر برای خرید در دسترس نیست..
        /// </summary>
        public static string CoursePurchase_CourseNotAvailable {
            get {
                return ResourceManager.GetString("CoursePurchase_CourseNotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to دوره‌های رایگان امکان خرید از طریق جریان نور را ندارند..
        /// </summary>
        public static string CoursePurchase_FreeCourseNotPurchasable {
            get {
                return ResourceManager.GetString("CoursePurchase_FreeCourseNotPurchasable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری خریدار فعال نمی‌باشد..
        /// </summary>
        public static string CoursePurchase_UserNotActive {
            get {
                return ResourceManager.GetString("CoursePurchase_UserNotActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to کاربر خریدار در سامانه یافت نشد..
        /// </summary>
        public static string CoursePurchase_UserNotFound {
            get {
                return ResourceManager.GetString("CoursePurchase_UserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to نرخ تبدیل ریال به نور باید بزرگتر از صفر باشد..
        /// </summary>
        public static string CoursePurchase_InvalidConversionRate {
            get {
                return ResourceManager.GetString("CoursePurchase_InvalidConversionRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to شناسه خارجی قلم معلق برای شارژ الزامی است..
        /// </summary>
        public static string TopUpRequest_PendingItemExternalIdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_PendingItemExternalIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to مبلغ اسنپ‌شات قیمت قلم معلق باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_PendingPriceMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_PendingPriceMustBeGreaterThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to اسنپ‌شات نرخ تبدیل برای قلم معلق باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_PendingRateMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_PendingRateMustBeGreaterThanZero", resourceCulture);
            }
        }
    }
}

