//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByeMoney.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByeMoney.Application.Resources.ApplicationErrors", typeof(ApplicationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تأیید شده ({0}) با مبلغ درخواست افزایش موجودی ({1}) مطابقت ندارد..
        /// </summary>
        public static string TopUpRequest_AmountMismatch {
            get {
                return ResourceManager.GetString("TopUpRequest_AmountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ افزایش موجودی باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_AmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_AmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ تأیید شده باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_ConfirmedAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_ConfirmedAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تراکنش خارجی الزامی است..
        /// </summary>
        public static string TopUpRequest_ExternalTransactionIdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_ExternalTransactionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه درخواست افزایش موجودی الزامی است..
        /// </summary>
        public static string TopUpRequest_IdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_IdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست افزایش موجودی با شناسه «{0}» یافت نشد..
        /// </summary>
        public static string TopUpRequest_NotFound {
            get {
                return ResourceManager.GetString("TopUpRequest_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش پرداخت نامعتبر است..
        /// </summary>
        public static string TopUpRequest_PaymentMethodInvalid {
            get {
                return ResourceManager.GetString("TopUpRequest_PaymentMethodInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلیل رد درخواست الزامی است..
        /// </summary>
        public static string TopUpRequest_RejectionReasonRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر الزامی است..
        /// </summary>
        public static string TopUpRequest_UserIdRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_UserIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر نباید بیشتر از ۱۰۰ کاراکتر باشد..
        /// </summary>
        public static string User_DisplayNameMaxLength {
            get {
                return ResourceManager.GetString("User_DisplayNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر الزامی است..
        /// </summary>
        public static string User_DisplayNameRequired {
            get {
                return ResourceManager.GetString("User_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل معتبر نیست..
        /// </summary>
        public static string User_PhoneInvalidFormat {
            get {
                return ResourceManager.GetString("User_PhoneInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل الزامی است..
        /// </summary>
        public static string User_PhoneRequired {
            get {
                return ResourceManager.GetString("User_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربر الزامی است..
        /// </summary>
        public static string User_RoleRequired {
            get {
                return ResourceManager.GetString("User_RoleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری با این شناسه Strapi قبلاً ثبت شده است..
        /// </summary>
        public static string User_StrapiIdAlreadyExists {
            get {
                return ResourceManager.GetString("User_StrapiIdAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر Strapi باید بزرگتر از صفر باشد..
        /// </summary>
        public static string User_StrapiUserIdInvalid {
            get {
                return ResourceManager.GetString("User_StrapiUserIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربر نامعتبر است..
        /// </summary>
        public static string User_UserTypeInvalid {
            get {
                return ResourceManager.GetString("User_UserTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر الزامی است..
        /// </summary>
        public static string Wallet_UserIdRequired {
            get {
                return ResourceManager.GetString("Wallet_UserIdRequired", resourceCulture);
            }
        }
    }
}
