//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByeMoney.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ByeMoney.Domain.Resources.DomainErrors", typeof(DomainErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودیت مورد نظر یافت نشد..
        /// </summary>
        public static string Common_EntityNotFound {
            get {
                return ResourceManager.GetString("Common_EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to «{0}» با شناسهٔ «{1}» یافت نشد..
        /// </summary>
        public static string Common_NotFound {
            get {
                return ResourceManager.GetString("Common_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست افزایش موجودی قبلاً با شناسه تراکنش خارجی متفاوتی تأیید شده است..
        /// </summary>
        public static string TopUpRequest_AlreadyConfirmedDifferentExternalId {
            get {
                return ResourceManager.GetString("TopUpRequest_AlreadyConfirmedDifferentExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ افزایش موجودی باید بزرگتر از صفر باشد..
        /// </summary>
        public static string TopUpRequest_AmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TopUpRequest_AmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تأیید درخواست افزایش موجودی ردشده وجود ندارد..
        /// </summary>
        public static string TopUpRequest_CannotConfirmRejected {
            get {
                return ResourceManager.GetString("TopUpRequest_CannotConfirmRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تأیید درخواست افزایش موجودی با وضعیت «{0}» وجود ندارد..
        /// </summary>
        public static string TopUpRequest_CannotConfirmStatus {
            get {
                return ResourceManager.GetString("TopUpRequest_CannotConfirmStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان رد درخواست افزایش موجودی در وضعیت «{0}» وجود ندارد. تنها درخواست‌های در انتظار قابل رد شدن هستند..
        /// </summary>
        public static string TopUpRequest_CannotRejectStatus {
            get {
                return ResourceManager.GetString("TopUpRequest_CannotRejectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دلیل رد درخواست الزامی است..
        /// </summary>
        public static string TopUpRequest_RejectionReasonRequired {
            get {
                return ResourceManager.GetString("TopUpRequest_RejectionReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربر نمی‌تواند خالی باشد..
        /// </summary>
        public static string User_DisplayNameRequired {
            get {
                return ResourceManager.GetString("User_DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل نمی‌تواند خالی باشد..
        /// </summary>
        public static string User_PhoneRequired {
            get {
                return ResourceManager.GetString("User_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه کاربر Strapi نامعتبر است..
        /// </summary>
        public static string User_StrapiInvalid {
            get {
                return ResourceManager.GetString("User_StrapiInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ افزایش اعتبار باید بزرگتر از صفر باشد..
        /// </summary>
        public static string Wallet_CreditMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Wallet_CreditMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ کسر اعتبار باید بزرگتر از صفر باشد..
        /// </summary>
        public static string Wallet_DebitMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Wallet_DebitMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دسترسی نمی‌تواند خالی باشد..
        /// </summary>
        public static string Permission_CodeRequired {
            get {
                return ResourceManager.GetString("Permission_CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش نمی‌تواند خالی باشد..
        /// </summary>
        public static string Role_NameRequired {
            get {
                return ResourceManager.GetString("Role_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول کافی نیست..
        /// </summary>
        public static string Wallet_InsufficientBalance {
            get {
                return ResourceManager.GetString("Wallet_InsufficientBalance", resourceCulture);
            }
        }
    }
}
